# Generated by Django 4.1.5 on 2023-01-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
